### ISSUE TITLE
Problem when trying to edit 

### ISSUE THREAD

**Issue by WuzUrDaddy** [zylklab/alfresco-share-online-edition-addon#12]
Hey, 

I have a problem with this amp. When I click the link to edit, nothing happens. I have this line that appeared on the Chrome network tool
![image](https://user-images.githubusercontent.com/12394684/44533109-15ef4200-a6f5-11e8-85f7-f2f32126d4a9.png)

My version of Alfresco is the 5.2.4 and I tried with LO v5.2 and LO v6.0. 

Do you know where the problem can come from? Thx

**Comment by CesarCapillas** [comment]
Hi:

In principle, the link should work if the protocol is correctly registered in your operating system. Do you ? If not please, check the docs.

I use Libreoffice 5.1 in Ubuntu 16.04 but, Libreoffice 5.2 or 6.0 should work too. From Alfresco point of view the addon was tested in Alfresco 5.2.3 with no problems. I use Chrome too.

What is your (client) operating system ? Do you have any blocker or warning in Chrome asking for open a file or something similar ?

Regards.
--C.

**Comment by WuzUrDaddy** [comment]
Hi, 

The protocole is correctly registered and set. I used [this](https://devops.profitbricks.com/tutorials/how-to-set-up-webdav-with-apache-on-centos-7/) to check it. My OS is CentOs 7. I don"t have anything on Chrome that could block it. I really don't know what could be wrong. I'll continue to investigate. 

Regards

**Comment by WuzUrDaddy** [comment]
Hi, 

I solved the problem. It came from the registration of the webdav protocol in Windows. I solved it and now it works. 

Thanks a lot for your help.
